# Generated by Django 3.2.15 on 2023-04-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursecatalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Здание',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название курса')),
                ('short_description', models.CharField(max_length=300, verbose_name='Короткое описание')),
                ('long_description', models.CharField(max_length=100000, verbose_name='Полное описание')),
                ('start_class', models.CharField(choices=[('1', '1 класс'), ('2', '2 класс'), ('3', '3 класс'), ('4', '4 класс'), ('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], max_length=100, verbose_name='Класс от')),
                ('end_class', models.CharField(choices=[('1', '1 класс'), ('2', '2 класс'), ('3', '3 класс'), ('4', '4 класс'), ('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], max_length=100, verbose_name='Класс до')),
                ('financing', models.CharField(choices=[('Бесплатно', 'Бесплатно'), ('Платно', 'Платно')], max_length=100, verbose_name='Финансирование')),
                ('link', models.URLField(verbose_name='Ссылка на курс')),
                ('format', models.CharField(choices=[('Очно', 'Очно'), ('Дистанционно', 'Дистанционно')], max_length=100, verbose_name='Формат проведения')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursecatalog.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Курс',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='department_icons/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Направленность',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресение', 'Воскресение')], max_length=500, verbose_name='День недели')),
                ('start_time', models.CharField(max_length=10, verbose_name='Время начала в формате 09:15')),
                ('end_time', models.CharField(max_length=10, verbose_name='Время окончания в формате 10:15')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursecatalog.course', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Занятие',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursecatalog.department', verbose_name='Направленность'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursecatalog.teacher', verbose_name='Учитель'),
        ),
    ]
